# Generated by Django 5.0.7 on 2025-09-21 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detection', '0001_initial'),
        ('scanning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contentmatch',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentmatch',
            name='scanned_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='scanning.scannedcontent'),
        ),
        migrations.AddField(
            model_name='detectionjob',
            name='scanned_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_jobs', to='scanning.scannedcontent'),
        ),
        migrations.AddField(
            model_name='detectionjob',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentmatch',
            name='detection_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='detection.detectionjob'),
        ),
        migrations.AddField(
            model_name='feedbackdata',
            name='content_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='detection.contentmatch'),
        ),
        migrations.AddField(
            model_name='feedbackdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modelperformancelog',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_logs', to='detection.aimodel'),
        ),
        migrations.AddField(
            model_name='protectedcontent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protected_content', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentmatch',
            name='protected_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='detection.protectedcontent'),
        ),
        migrations.AlterUniqueTogether(
            name='contentmatch',
            unique_together={('protected_content', 'scanned_content')},
        ),
    ]
