# Generated by Django 5.0.7 on 2025-09-21 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scanning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='platformcredential',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_credentials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_jobs', to='scanning.platform'),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scannedcontent',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanning.platform'),
        ),
        migrations.AddField(
            model_name='scannedcontent',
            name='scan_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanned_content', to='scanning.scanjob'),
        ),
        migrations.AddField(
            model_name='scanschedule',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_schedules', to='scanning.platform'),
        ),
        migrations.AddField(
            model_name='scanschedule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='platformcredential',
            unique_together={('user', 'platform')},
        ),
        migrations.AddIndex(
            model_name='scannedcontent',
            index=models.Index(fields=['content_hash'], name='scanned_con_content_da1038_idx'),
        ),
        migrations.AddIndex(
            model_name='scannedcontent',
            index=models.Index(fields=['published_at'], name='scanned_con_publish_22ccb8_idx'),
        ),
    ]
