# Generated by Django 5.0.7 on 2025-09-25 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='platformcredential',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='scannedcontent',
            name='scan_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanned_content', to='scanning.scanjob'),
        ),
    ]
