# Generated by Django 5.0.7 on 2025-09-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourtOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('injunction', 'Injunction'), ('subpoena', 'Subpoena'), ('seizure', 'Seizure Order'), ('other', 'Other')], max_length=20)),
                ('case_number', models.CharField(max_length=100, unique=True)),
                ('issuing_court', models.CharField(max_length=255)),
                ('issue_date', models.DateField()),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('summary', models.TextField()),
                ('full_document_path', models.FileField(blank=True, null=True, upload_to='legal_documents/court_orders/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'court_orders',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='DMCAClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('original_content_url', models.URLField(blank=True, null=True)),
                ('infringing_content_url', models.URLField()),
                ('claimant_name', models.CharField(max_length=255)),
                ('claimant_email', models.EmailField(max_length=254)),
                ('claimant_company', models.CharField(blank=True, max_length=255, null=True)),
                ('declaration_of_accuracy', models.BooleanField(default=False)),
                ('authorization_to_act', models.BooleanField(default=False)),
                ('good_faith_belief', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('takedown_issued', 'Takedown Issued'), ('disputed', 'Disputed'), ('resolved', 'Resolved')], default='draft', max_length=20)),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('resolution_date', models.DateTimeField(blank=True, null=True)),
                ('generated_document_path', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dmca_claims',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='evidence/')),
                ('url_snapshot', models.URLField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('is_tamper_proof', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'evidence_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Jurisdiction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'jurisdictions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LegalCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_compliant', models.BooleanField(default=True)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'legal_compliance',
                'ordering': ['-last_checked'],
            },
        ),
    ]
