# Generated by Django 5.0.7 on 2025-09-21 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detection', '0002_initial'),
        ('legal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courtorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='court_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dmcaclaim',
            name='content_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dmca_claims', to='detection.contentmatch'),
        ),
        migrations.AddField(
            model_name='dmcaclaim',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dmca_claims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evidencelog',
            name='content_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_logs', to='detection.contentmatch'),
        ),
        migrations.AddField(
            model_name='evidencelog',
            name='court_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_logs', to='legal.courtorder'),
        ),
        migrations.AddField(
            model_name='evidencelog',
            name='dmca_claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_logs', to='legal.dmcaclaim'),
        ),
        migrations.AddField(
            model_name='evidencelog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courtorder',
            name='jurisdiction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='court_orders', to='legal.jurisdiction'),
        ),
        migrations.AddField(
            model_name='legalcompliance',
            name='jurisdiction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_records', to='legal.jurisdiction'),
        ),
        migrations.AddField(
            model_name='legalcompliance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_compliance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='legalcompliance',
            unique_together={('user', 'jurisdiction')},
        ),
    ]
